"""Make password nullable and add auth_provider

Revision ID: 46f936854c1a
Revises: 7e3f989a408e
Create Date: 2025-05-11 15:33:46.879793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f936854c1a'
down_revision = '7e3f989a408e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_provider', sa.String(length=20), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.BLOB(),
               type_=sa.String(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.BLOB(),
               nullable=False)
        batch_op.drop_column('auth_provider')

    # ### end Alembic commands ###
