"""Initial migration

Revision ID: 7e3f989a408e
Revises: 
Create Date: 2025-05-11 15:31:25.032408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3f989a408e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.LargeBinary(length=120),
               nullable=False)
        batch_op.drop_column('auth_provider')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_provider', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.LargeBinary(length=120),
               type_=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
